//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AbcNotation.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


	using MusicaMinimalista.Objects.Music;
	using MusicaMinimalista.Objects.Utils;

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="AbcNotationParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IAbcNotationListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] AbcNotationParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] AbcNotationParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeader([NotNull] AbcNotationParser.HeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeader([NotNull] AbcNotationParser.HeaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.x_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterX_field([NotNull] AbcNotationParser.X_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.x_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitX_field([NotNull] AbcNotationParser.X_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.t_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterT_field([NotNull] AbcNotationParser.T_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.t_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitT_field([NotNull] AbcNotationParser.T_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.m_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterM_field([NotNull] AbcNotationParser.M_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.m_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitM_field([NotNull] AbcNotationParser.M_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.q_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ_field([NotNull] AbcNotationParser.Q_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.q_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ_field([NotNull] AbcNotationParser.Q_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.l_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterL_field([NotNull] AbcNotationParser.L_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.l_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitL_field([NotNull] AbcNotationParser.L_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.k_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterK_field([NotNull] AbcNotationParser.K_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.k_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitK_field([NotNull] AbcNotationParser.K_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.score"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScore([NotNull] AbcNotationParser.ScoreContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.score"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScore([NotNull] AbcNotationParser.ScoreContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.v_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterV_field([NotNull] AbcNotationParser.V_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.v_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitV_field([NotNull] AbcNotationParser.V_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.music_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMusic_elem([NotNull] AbcNotationParser.Music_elemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.music_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMusic_elem([NotNull] AbcNotationParser.Music_elemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.ignored_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIgnored_elem([NotNull] AbcNotationParser.Ignored_elemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.ignored_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIgnored_elem([NotNull] AbcNotationParser.Ignored_elemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.chord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChord([NotNull] AbcNotationParser.ChordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.chord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChord([NotNull] AbcNotationParser.ChordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.note"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNote([NotNull] AbcNotationParser.NoteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.note"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNote([NotNull] AbcNotationParser.NoteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.noteduration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoteduration([NotNull] AbcNotationParser.NotedurationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.noteduration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoteduration([NotNull] AbcNotationParser.NotedurationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.pitch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPitch([NotNull] AbcNotationParser.PitchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.pitch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPitch([NotNull] AbcNotationParser.PitchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AbcNotationParser.bar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBar([NotNull] AbcNotationParser.BarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AbcNotationParser.bar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBar([NotNull] AbcNotationParser.BarContext context);
}
